version: "3.9"

services:

  dashboard:
    build: .
    container_name: dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
    - "9090:9090"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--web.external-url=http://98.92.57.61/prometheus/"
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://98.92.57.61/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: